FROM registry.access.redhat.com/ubi8/ubi AS container-ansible-build
MAINTAINER Ben Colby-Sexton bcs@redhat.com
LABEL org.opencontainers.image.authors="Ben Colby-Sexton bcs@redhat.com"
LABEL name=container-ocp-ansible
LABEL org.opencontainers.image.base.name=container-ocp-ansible
LABEL description="A basic container for executing Ansible, and OC/OPM. Should usually be run interactively."

RUN mkdir -p /mnt/rootfs
RUN yum repolist
RUN yum install\
 coreutils-single glibc-minimal-langpack\
 python38 libgcc vim\
 --installroot /mnt/rootfs\
 --releasever 8\
 --setopt=module_platform_id=platform:el8\
 --setopt=install_weak_deps=false\
 --setopt=tsflags=nodocs\
 --setopt=override_install_langs=en_US.utf8\
 -y
RUN curl https://bootstrap.pypa.io/get-pip.py -o /mnt/rootfs/get-pip.py

ARG OCP_RELEASE=latest
RUN curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_RELEASE/openshift-client-linux.tar.gz -o openshift-client-linux.tar.gz
RUN tar xf openshift-client-linux.tar.gz -C /mnt/rootfs/bin/ oc kubectl
RUN rm -f openshift-client-linux.tar.gz

ARG OCP_RELEASE=latest
RUN curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_RELEASE/opm-linux.tar.gz -o opm-linux.tar.gz
RUN tar xf opm-linux.tar.gz -C /mnt/rootfs/bin/ opm
RUN rm -f opm-linux.tar.gz
RUN rm -rf /mnt/rootfs/var/cache/*
RUN rm -rf /mnt/rootfs/var/lib/rpm

FROM scratch AS container-ansible
COPY --from=container-ansible-build /mnt/rootfs/ /
RUN python3 get-pip.py
RUN rm get-pip.py
RUN python3 -m pip --no-cache-dir install setuptools-rust wheel
RUN python3 -m pip --no-cache-dir install ansible paramiko "pywinrm>=0.3.0" netaddr openshift requests-oauth
RUN python3 -m pip --no-cache-dir uninstall setuptools-rust wheel pip -y

ENV OPENSHIFT_API_URL=''
ENV OPENSHIFT_API_INSECURE_CERTS=''
ENV OPENSHIFT_API_USERNAME=''
ENV OPENSHIFT_API_PASSWORD=''

WORKDIR /ansible
VOLUME /ansible
CMD /bin/sh
